name: unit tests

on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Set LA timezone
      run: |
        sudo systemsetup -settimezone America/Los_Angeles

    - uses: actions/checkout@v3

    - name: Build and Test
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: ./KosherCocoa.xcodeproj
        destination: platform=macOS
        scheme: KosherCocoaTests
        action: test

    - name: Reset timezone to default (UTC)
      run: |
        sudo systemsetup -settimezone UTC
