name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Build and Test
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: KosherCocoa.xcodeproj
        scheme: KosherCocoa
        destination: platform=macOS
        action: test
